// AUTO-GENERATED by demo-video skill — edit values, not structure
export const FPS = 30;
export const W = 1920;
export const H = 1080;

// Theme synced to web/app/globals.css tokens (dark variant for video)
export const COLORS = {
  bg: "#0a0a14",
  bgCard: "rgba(22,21,38,0.72)",
  accent: "#5b51e8",
  accentDim: "#312c8f",
  accentBright: "#8b83f4",
  teal: "#14b8a6",
  white: "#f2f1f8",
  offWhite: "#aaa7bd",
  muted: "#5e5b72",
  border: "rgba(91,81,232,0.25)",
  red: "#ef4444",
  amber: "#f59e0b",
  cyan: "#22d3ee",
};

export const TERMINAL = {
  bg: "#0c0c18",
  text: "#cfcde0",
  green: "#3fb950",
  yellow: "#d29922",
  red: "#f85149",
  blue: "#58a6ff",
  purple: "#bc8cff",
  prompt: "#8b949e",
};

export const SCENE_GAP = Math.round(1.5 * FPS);

// Real ffprobe durations (seconds * FPS)
export const AUDIO_DURATIONS = {
  hook: Math.round(9.552 * FPS), // 287
  problem: Math.round(14.736 * FPS), // 442
  authoring: Math.round(16.848 * FPS), // 505
  loop: Math.round(20.04 * FPS), // 601
  onchain: Math.round(16.776 * FPS), // 503
  settlement: Math.round(13.656 * FPS), // 410
  close: Math.round(13.056 * FPS), // 392
} as const;

// Scene visual time: audio + gap (+ extra hold for recordings / close fade)
export const SCENE_DURATIONS = {
  hook: AUDIO_DURATIONS.hook + SCENE_GAP + 45,
  problem: AUDIO_DURATIONS.problem + SCENE_GAP + 15,
  authoring: AUDIO_DURATIONS.authoring + SCENE_GAP + 100, // recording runs past narration
  loop: AUDIO_DURATIONS.loop + SCENE_GAP + 15,
  onchain: AUDIO_DURATIONS.onchain + SCENE_GAP + 15,
  settlement: AUDIO_DURATIONS.settlement + SCENE_GAP + 105,
  close: AUDIO_DURATIONS.close + SCENE_GAP + 60, // hold + slow fade to black
} as const;

export const CROSSFADE = 24;

export const TOTAL_FRAMES =
  Object.values(SCENE_DURATIONS).reduce((a, b) => a + b, 0) -
  CROSSFADE * (Object.keys(SCENE_DURATIONS).length - 1);

export const AUDIO_FILES: Record<keyof typeof SCENE_DURATIONS, string> = {
  hook: "audio/hook.mp3",
  problem: "audio/problem.mp3",
  authoring: "audio/authoring.mp3",
  loop: "audio/loop.mp3",
  onchain: "audio/onchain.mp3",
  settlement: "audio/settlement.mp3",
  close: "audio/close.mp3",
};

// Real on-chain data (Real-Only Principle — verified on Somnia testnet)
export const ONCHAIN = {
  covenant: "0x152432d1B863C0A0645D86452a23F9C16077C28A",
  createTx: "0x7259c134a3cec8cd2d2ee80a81d945b6ad24b98cfd17681140ebc4f1ac167834",
  receiptUrl: "agents.testnet.somnia.network/receipts/5358074",
  chain: "Somnia Testnet · 50312",
  buffer: "33 STT",
  liveUrl: "covenant-beta.vercel.app",
  repo: "github.com/ajanaku1/covenant",
};

// The canonical agreement text typed in the authoring scene
export const DEMO_CLAUSE =
  "Pay the freelancer 200 USDC when the site at https://acme.build is live and mentions Somnia. Check daily for 7 days. Refund me if it isn't met by the deadline.";

export const SOCIAL_FPS = 30;
export const SOCIAL_W = 1080;
export const SOCIAL_H = 1920;
export const SOCIAL_DURATION = 11 * FPS;
